site_name: Sara
theme:
  name: material
  direction: 
  font:
    code: Vazirmatn
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
markdown_extensions:
  - attr_list
  - def_list
plugins:
  - blog:
      post_excerpt_separator: <!-- more -->
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://fosstodon.org/@squidfunk
    - icon: fontawesome/solid/paper-plane
      link: mailto:<saraabbasi847@gmail.com>
  alternate:
    - name: English
      link: /en/ 
      lang: en
      direction: ltr
    - name: Persian
      link: /fe/
      lang: fe
      direction: rtl
copyright: Copyright &copy; 2024 Sara Abbasi
